version: '3.5'

services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    env_file:
      - ./.env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/auth_api_data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d auth_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - cinema

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - ./.env
    volumes:
      - $HOME/redis/data:/var/lib/redis/data
    networks:
      - cinema

  auth:
    container_name: auth
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    networks:
      - cinema

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth
    ports:
      - "80:80"
    networks:
      - cinema

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "16685:16685"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    depends_on:
      - auth
    networks:
      - cinema

networks:
  cinema:
    name: cinema
